### ISSUE TITLE
USB FCC Controller

### ISSUE THREAD

**Issue by fusion79** [uriba107/fcc_controller#1]
URI,
   Hi this is Fusion (aka viper44). Thanks for your contribution to making the fcc controller. I do have an issue with it and maybe you can help me and others. I have been having issues as far as the controller working on 3 separate computers in different ways. My laptop in a USB 3.0 port is working flawlessly with all current drivers installed for my usb hub on my laptop all buttons and axis work. The second pc which is my desk pc for everyday use as far as bills, letters, etc. works with most of the buttons till you get to the tms, dms, cms inputs and the nws buttons. They don't work or intermittent. All of the drivers are current. The axis' do work. This is plugging it into the usb 2.0 port on motherobard, usb 3.0 port on motherboard, and powered usb 2.0 hub plugged into a usb 2.0 port on motherboard. Last my simulator PC when I plug it into the usb 2.0 and 3.1 ports on my motherboard as well as powered usb 2.0 hub plugged into usb 2.0 on motherboard only the axis, 1st detent trigger, pickle buttons work and the hat only works in a few directions. Please help me with this issue as I really want to use your controller. 
I have told quite a few people about your controllers, ded, pfld, ffl, etc. They are interested but hope the bugs will be fixed.
Thanks in advance.

Matt "Fusion"

**Comment by uriba107** [comment]
closing
